# Deployment scaffold

version: '3.8'

services:
  # Gateway
  #   build: ../services/gateway-service
  #   ports: ["3000:3000"]

  # Customer service
  #   build: ../services/customer-service
  #   ports: ["3001:3001"]

  # Booking service
  #   build: ../services/booking-service
  #   ports: ["3002:3002"]

  # Payment service
  #   build: ../services/payment-service
  #   ports: ["3003:3003"]

  # Fare estimation service
  #   build: ../services/fare-estimation-service
  #   ports: ["3004:3004"]

  # Location service
  #   build: ../services/location-service
  #   ports: ["3005:3005"]

  # Web application
  #   build: ../web-app
  #   ports: ["8080:8080"]
