# Dockerfile for customer-service
# TODO: Complete during deployment phase (Google Cloud Run)

FROM node:20-alpine

WORKDIR /app

# TODO: COPY package*.json ./
# TODO: RUN npm install --production
# TODO: COPY . .

EXPOSE 3001

CMD ["node", "src/index.js"]
